### ISSUE TITLE
点击视频另存为出错

### ISSUE THREAD

**Issue by tangming2010** [tpnet/ImoocVideoMerge#1]
视频另存为时，崩溃，机型：vivo X7

**Comment by tpnet** [comment]
@tangming2010  你好，我这边没有这个手机，可以看一下奔溃日志吗？

**Comment by tangming2010** [comment]
我没有在模拟器中运行，也不会Android，所以不知道怎么看日志。

**Comment by rehack** [comment]
我也遇到了这样的问题，不能另存单个视频。Android7.0
![screenshot_2017-03-31-21-40-03-942_com tpnet imoocvideomerge](https://cloud.githubusercontent.com/assets/9047357/24552917/e509e5c2-165a-11e7-9e96-2e7e6e37f8cf.png)

**Comment by tpnet** [comment]
@codesboy  在首页那里保存整个文件夹可以吗？  手机什么型号，这个提示是读取不到 已经下载好的文件，可能手机或者系统不一样，路径不对。

**Comment by rehack** [comment]
在首页也不能复制，小米5手机
![_20170401094234](https://cloud.githubusercontent.com/assets/9047357/24574089/fb7401ac-16bf-11e7-9f0f-409ba40aefb8.jpg)
![qq 20170401094212](https://cloud.githubusercontent.com/assets/9047357/24574093/0579238a-16c0-11e7-83d4-8c775f79665f.png)
![_20170401093647](https://cloud.githubusercontent.com/assets/9047357/24574094/0581bb12-16c0-11e7-96fd-71ebe282ed8d.png)

**Comment by tpnet** [comment]
@codesboy   尴尬了，我刚刚拿这个手机测试了，完全正常。

**Comment by rehack** [comment]
@tpnet 如果你也是小米5 可以远程操作

**Comment by tpnet** [comment]
vip视频暂时还不能另存为
